from Group import Group
from Samples import *
import palette

"""

DYZ = Group('DYZ',
            [ZeeNp0Excl_Mll10to60,
             ZeeNp1Excl_Mll10to60,
             ZeeNp2Excl_Mll10to60,
             ZeeNp3Excl_Mll10to60,
             ZeeNp4Excl_Mll10to60,
             ZeeNp5Incl_Mll10to60,
             ZmumuNp0Excl_Mll10to60,
             ZmumuNp1Excl_Mll10to60,
             ZmumuNp2Excl_Mll10to60,
             ZmumuNp3Excl_Mll10to60,
             ZmumuNp4Excl_Mll10to60,
             ZmumuNp5Incl_Mll10to60,
             ZtautauNp0Excl_Mll10to60,
             ZtautauNp1Excl_Mll10to60,
             ZtautauNp2Excl_Mll10to60,
             ZtautauNp3Excl_Mll10to60,
             ZtautauNp4Excl_Mll10to60,
             ZtautauNp5Incl_Mll10to60],
             factor = 1.0,
             color = palette.blue,
             style = 'fill',
             legendLabel = 'DYZ+Jets',
             stack = True,
             classification = 'BG'
             )


WJets = Group('WJets',
              [WenuNp0,
               WenuNp1,
               WenuNp2,
               WenuNp3,
               WenuNp4,
               WenuNp5incl,
               WmunuNp0,
               WmunuNp1,
               WmunuNp2,
               WmunuNp3,
               WmunuNp4,
               WmunuNp5incl,
               WtaunuNp0,
               WtaunuNp1,
               WtaunuNp2,
               WtaunuNp3,
               WtaunuNp4,
               WtaunuNp5incl],
              factor = 1.0,
              color = palette.orange,
              style = 'fill',
              legendLabel =  'W+Jets',
              stack = True,
              classification = 'BG'
              )

WW = Group('WW',
           [WWlnulnuNp0,
            WWlnulnuNp1,
            WWlnulnuNp2,
            WWlnulnuNp3,
            WWqqlnuNp0,
            WWqqlnuNp1,
            WWqqlnuNp2,
            WWqqlnuNp3,
            WpWmenuenu,
            WpWmenumunu,
            WpWmenutaunu,
            WpWmmunuenu,
            WpWmmunumunu,
            WpWmmunutaunu,
            WpWmtaunuenu,
            WpWmtaunumunu,
            WpWmtaunutaunu],
           factor = 1.0,
           color = palette.pink,
           style = 'fill',
           legendLabel = 'WW',
           stack = True,
           classification = 'BG'
           )

WZ = Group('WZ',
           [WZ],
           factor = 1.0,
           color = palette.skyblue,
           style = 'fill',
           legendLabel = 'WZ',
           stack = True,
           classification = 'BG'
           )

ZJets = Group('ZJets',
              [ZeeNp0,
               ZeeNp1,
               ZeeNp2,
               ZeeNp3,
               ZeeNp4,
               ZeeNp5incl,
               ZmumuNp0,
               ZmumuNp1,
               ZmumuNp2,
               ZmumuNp3,
               ZmumuNp4,
               ZmumuNp5incl,
               ZtautauNp0,
               ZtautauNp1,
               ZtautauNp2,
               ZtautauNp3,
               ZtautauNp4,
               ZtautauNp5incl],
               factor = 1.0,
              color = palette.green,
              style = 'fill',
              legendLabel = 'Z+Jets',
              stack = True,
              classification = 'BG'
              )

ZZ = Group('ZZ',
           [ZZ],
           factor = 1.0,
           color = palette.purple,
           style = 'fill',
           legendLabel = 'ZZ',
           stack = True,
           classification = 'BG'
           )

SingleTop = Group('SingleTop',
                  [SingleTopSChanWenu,
                   SingleTopSChanWmunu,
                   SingleTopSChanWtaunu,
                   SingleTopWtChanIncl,
                   singletop_tchan_e,
                   singletop_tchan_mu,
                   singletop_tchan_tau],
            factor = 1.0,
            color = palette.grey,
            style = 'fill',
            legendLabel = 'SingleTop',
            stack = True,
            classification = 'BG'
            )


ttbar_allh = Group('ttbar_allh',
                     [ttbar_allhad],
                     factor = 1.0,
                     color = palette.peach,
                     style = 'fill',
                     legendLabel = 'ttbar_allhad',
                     stack = True,
                     classification = 'BG'
                     )

ttbar_dilep = Group('ttbar_dilep',
                    [ttbar_dilepton],
                    factor = 1.0,
                    color = palette.slime,
                    style = 'fill',
                    legendLabel = 'ttbar_dilep',
                    stack = True,
                    classification = 'BG'
                    )

ttbar_lepfil = Group('ttbar_lepfil',
                     [ttbar],
                     factor = 1.0,
                     color = palette.indigo,
                     style = 'fill',
                     legendLabel = 'ttbar_lepfil',
                     stack = True,
                     classification = 'BG'
                     )

Top = Group('Top', #includes all Top samples except for ttbar_dilepton (included in ttbar--lepfil)
            [ttbar,
             SingleTopSChanWenu,
             SingleTopSChanWmunu,
             SingleTopSChanWtaunu,
             SingleTopWtChanIncl,
             singletop_tchan_e,
             singletop_tchan_mu,
             singletop_tchan_tau,
             ttbar_allhad
             ],
            factor = 1.0,
            color = palette.brown,
            style = 'fill',
            legendLabel = 'Top',
            stack = True,
            classification = 'BG'
            )


AllBG = Group('AllBG',
              [ttbar,
             SingleTopSChanWenu,
             SingleTopSChanWmunu,
             SingleTopSChanWtaunu,
             SingleTopWtChanIncl,
             singletop_tchan_e,
             singletop_tchan_mu,
             singletop_tchan_tau,
             ttbar_allhad,
             ZZ,
             ZeeNp0,
             ZeeNp1,
             ZeeNp2,
             ZeeNp3,
             ZeeNp4,
             ZeeNp5incl,
             ZmumuNp0,
             ZmumuNp1,
             ZmumuNp2,
             ZmumuNp3,
             ZmumuNp4,
             ZmumuNp5incl,
             ZtautauNp0,
             ZtautauNp1,
             ZtautauNp2,
             ZtautauNp3,
             ZtautauNp4,
             ZtautauNp5incl,
             WZ,
             WWlnulnuNp0,
             WWlnulnuNp1,
             WWlnulnuNp2,
             WWlnulnuNp3,
             WWqqlnuNp0,
             WWqqlnuNp1,
             WWqqlnuNp2,
             WWqqlnuNp3,
             WpWmenuenu,
             WpWmenumunu,
             WpWmenutaunu,
             WpWmmunuenu,
             WpWmmunumunu,
             WpWmmunutaunu,
             WpWmtaunuenu,
             WpWmtaunumunu,
             WpWmtaunutaunu,
             WenuNp0,
             WenuNp1,
             WenuNp2,
             WenuNp3,
             WenuNp4,
             WenuNp5incl,
             WmunuNp0,
             WmunuNp1,
             WmunuNp2,
             WmunuNp3,
             WmunuNp4,
             WmunuNp5incl,
             WtaunuNp0,
             WtaunuNp1,
             WtaunuNp2,
             WtaunuNp3,
             WtaunuNp4,
             WtaunuNp5incl,
             ZeeNp0Excl_Mll10to60,
             ZeeNp1Excl_Mll10to60,
             ZeeNp2Excl_Mll10to60,
             ZeeNp3Excl_Mll10to60,
             ZeeNp4Excl_Mll10to60,
             ZeeNp5Incl_Mll10to60,
             ZmumuNp0Excl_Mll10to60,
             ZmumuNp1Excl_Mll10to60,
             ZmumuNp2Excl_Mll10to60,
             ZmumuNp3Excl_Mll10to60,
             ZmumuNp4Excl_Mll10to60,
             ZmumuNp5Incl_Mll10to60,
             ZtautauNp0Excl_Mll10to60,
             ZtautauNp1Excl_Mll10to60,
             ZtautauNp2Excl_Mll10to60,
             ZtautauNp3Excl_Mll10to60,
             ZtautauNp4Excl_Mll10to60,
             ZtautauNp5Incl_Mll10to60],
             factor = 1.0,
             color = palette.blue,
             style = 'fill',
             legendLabel = 'AllBG',
             stack = True,
             classification = 'BG'
             )

WH = Group('WH',
           [WH125_tautauhh],
           factor = 1.0,
           color = palette.red,
           style = 'line',
           legendLabel = 'WH',
           stack = False,
           classification = 'SIG'
           )
"""
ZH = Group('ZH',
           [ZH125_tautauhh],
           factor = 1.0,
           color = palette.red,
           style = 'line',
           legendLabel = 'ZH',
           stack = False,
           classification = 'SIG'
           )

        
