from Group import Group
from Samples import *
import palette

Data = Group('Data',
             [Egamma,
              JetTauEtmiss,
              Muons],
              factor = 1.0,
              color = palette.black,
              style = 'points',
              legendLabel = 'Data',
              stack = False,
              classification = 'DATA'
              )
WJets = Group('WJets',
              [WenuNp0_Auto,
               WmunuNp0_Auto,
               WenuNp1_Auto,
               WenuNp2_Auto,
               WenuNp3_Auto,
               WenuNp4_Auto,
               WenuNp5incl_Auto,
               WmunuNp1_Auto,
               WmunuNp2_Auto,
               WmunuNp3_Auto,
               WmunuNp4_Auto,
               WmunuNp5incl_Auto,
               WtaunuNp0_Auto,
               WtaunuNp1_Auto,
               WtaunuNp2_Auto,
               WtaunuNp3_Auto,
               WtaunuNp4_Auto,
               WtaunuNp5incl_Auto
               ],
               factor = 1.0,
               color = palette.green,
               style = 'fill',
               legendLabel = 'WJets',
               stack = True,
#stack = False,
               classification = 'BG'
               )
WJetsMedID = Group('WJetsMedID',
                   [WenuNp0_medID,
                    WenuNp1_medID,
                    WenuNp2_medID,
                    WenuNp3_medID,
                    WenuNp4_medID,
                    WenuNp5incl_medID,
                    WmunuNp0_medID,
                    WmunuNp1_medID,
                    WmunuNp2_medID,
                    WmunuNp3_medID,
                    WmunuNp4_medID,
                    WmunuNp5incl_medID,
                    WtaunuNp0_medID,
                    WtaunuNp1_medID,
                    WtaunuNp2_medID,
                    WtaunuNp3_medID,
                    WtaunuNp4_medID,
                    WtaunuNp5incl_medID],
                    factor = 1.0,
                    color = palette.green,
                    style = 'fill',
                    legendLabel = 'WJetsMedID',
                    stack = True,
                    classification = 'BG'
                    )
     
ZJets = Group('ZJets',
[ZeeNp0_Auto,
               ZmumuNp0_Auto,
               ZeeNp1_Auto,
               ZeeNp2_Auto,
               ZeeNp3_Auto,
               ZeeNp4_Auto,
               ZeeNp5incl_Auto,
               ZmumuNp1_Auto,
               ZmumuNp2_Auto,
               ZmumuNp3_Auto,
               ZmumuNp4_Auto,
               ZmumuNp5incl_Auto,
               ZeeNp0Excl_Mll10to60,
               ZeeNp1Excl_Mll10to60,
               ZeeNp2Excl_Mll10to60,
               ZeeNp3Excl_Mll10to60,
               ZeeNp4Excl_Mll10to60,
               ZeeNp5Incl_Mll10to60,
               ZmumuNp0Excl_Mll10to60,
               ZmumuNp1Excl_Mll10to60,
               ZmumuNp2Excl_Mll10to60,
               ZmumuNp3Excl_Mll10to60,
               ZmumuNp4Excl_Mll10to60,
               ZmumuNp5Incl_Mll10to60,
               ZtautauNp0Excl_Mll10to60,
               ZtautauNp0_Auto,
               ZtautauNp1_Auto,
               ZtautauNp2_Auto,
               ZtautauNp3_Auto,
               ZtautauNp4_Auto,
               ZtautauNp5incl_Auto,
               ZtautauNp1Excl_Mll10to60,
               ZtautauNp2Excl_Mll10to60,
               ZtautauNp3Excl_Mll10to60,
               ZtautauNp4Excl_Mll10to60,
               ZtautauNp5Incl_Mll10to60],
#factor = 0.80916,#factor when plotting is_WHlephad
factor = 1.0,
               color = palette.blue,
               style = 'fill',
               legendLabel = 'ZJets',
               stack = True,
               classification = 'BG'
               )
ZJetsAFII = Group('ZJetsAFII',
                  [ZeeNp0_AFII,
                   ZmumuNp0_AFII,
                   ZeeNp1_AFII,
                   ZeeNp2_AFII,
                   ZeeNp3_AFII,
                   ZeeNp4_AFII,
                   ZeeNp5incl_AFII,
                   ZmumuNp1_AFII,
                   ZmumuNp2_AFII,
                   ZmumuNp3_AFII,
                   ZmumuNp4_AFII,
                   ZmumuNp5incl_AFII],
                   factor = 1.0,
                   color = palette.green,
                   style = 'fill',
                   legendLabel = 'ZJetsAFII',
                   stack = True,
                   classification = 'BG'
                   )
                   
                   
    

    

                    
                   
WlepnuNp0 = Group('WlepnuNp0',
                  [WenuNp0_Auto,
                  WmunuNp0_Auto],
                  factor = 1.0,
                  color = palette.orange,
                  style = 'fill',
                  legendLabel = 'WlepnuNp0',
                  stack = True,
                  classification = 'BG'
    )
WlepnuJets = Group('WlepnuJets',
[#WenuNp1_Auto,
#WenuNp2_Auto,
#                   WenuNp3_Auto,
#                   WenuNp4_Auto,
#                   WenuNp5incl_Auto,
#                   WmunuNp1_Auto,
#WmunuNp2_Auto,
#                   WmunuNp3_Auto,
#                   WmunuNp4_Auto,
#                   WmunuNp5incl_Auto],
],
                    factor = 1.0,
                    color = palette.darkpink,
                    style = 'fill',
                    legendLabel = 'WlepnuJets',
                    stack = True,
                    classification = 'BG'
    )
WtaunuNp0 = Group('WtaunuNp0',
                  [WtaunuNp0_Auto],
                  factor = 1.0,
                  color = palette.green,
                  style = 'fill',
                  legendLabel = 'WtaunuNp0',
                  stack = True,
                  classification = 'BG'
                  )
WtaunuJets = Group('WtaunuJets',
                   [WtaunuNp1_Auto,
                    WtaunuNp2_Auto,
                    WtaunuNp3_Auto,
                    WtaunuNp4_Auto,
                    WtaunuNp5incl_Auto],
                    factor = 1.0,
                    color = palette.teal,
                    style = 'fill',
                    legendLabel = 'WtaunuJets',
                    stack = True,
                    classification = 'BG'
                  )
WJetsAFII = Group('WJetsAFII',
                  [WenuNp0_AFII,
                   WenuNp1_AFII,
                   WenuNp2_AFII,
                   WenuNp3_AFII,
                   WenuNp4_AFII,
                   WenuNp5incl_AFII,
                   WmunuNp0_AFII,
                   WmunuNp1_AFII,
                   WmunuNp2_AFII,
                   WmunuNp3_AFII,
                   WmunuNp4_AFII,
                   WmunuNp5incl_AFII,
                   WtaunuNp0_AFII,
                   WtaunuNp1_AFII,
                   WtaunuNp2_AFII,
                   WtaunuNp3_AFII,
                   WtaunuNp4_AFII,
                   WtaunuNp5incl_AFII],
                   factor = 1.0,
                   color = palette.blue,
                   style = 'fill',
                   legendLabel = 'WJetsAFII',
                   stack = True,
                   classification = 'BG'
                   )
ZleplepNp0 = Group('ZleplepNp0',
                   [ZeeNp0Excl_Mll10to60,
                    ZmumuNp0Excl_Mll10to60,
                    ZeeNp0_Auto,
                    ZmumuNp0_Auto],
                    factor = 1.0,
                    color = palette.skyblue,
                    style = 'fill',
                    legendLabel = 'ZleplepNp0',
                    stack = True,
                    classification = 'BG'
                  )
ZleplepJets = Group('ZleplepJets',
                    [ZeeNp1_Auto,
                     ZeeNp2_Auto,
                     ZeeNp3_Auto,
                     ZeeNp4_Auto,
                     ZeeNp5incl_Auto,
                     ZmumuNp1_Auto,
                     ZmumuNp2_Auto,
                     ZmumuNp3_Auto,
                     ZmumuNp4_Auto,
                     ZmumuNp5incl_Auto,
                     ZeeNp1Excl_Mll10to60,
                     ZeeNp2Excl_Mll10to60,
                     ZeeNp3Excl_Mll10to60,
                     ZeeNp4Excl_Mll10to60,
                     ZeeNp5Incl_Mll10to60,
                     ZmumuNp1Excl_Mll10to60,
                     ZmumuNp2Excl_Mll10to60,
                     ZmumuNp3Excl_Mll10to60,
                     ZmumuNp4Excl_Mll10to60,
                     ZmumuNp5Incl_Mll10to60,
                     ],
                     factor = 1.0,
                     color = palette.darkorange,
                     style = 'fill',
                     legendLabel = 'ZleplepJets',
                     stack = True,
                     classification = 'BG',
                     )
Ztautau = Group('Ztautau',
                [ZtautauNp0Excl_Mll10to60,
                 ZtautauNp0_Auto],
                 factor = 1.0,
                 color = palette.indigo,
                 style = 'fill',
                 legendLabel = 'Ztautau',
                 stack = True,
                 classification = 'BG',
                 )
ZtautauJets = Group('ZtautauJets',
                    [ZtautauNp1_Auto,
                     ZtautauNp2_Auto,
                     ZtautauNp3_Auto,
                     ZtautauNp4_Auto,
                     ZtautauNp5incl_Auto,
                     ZtautauNp1Excl_Mll10to60,
                     ZtautauNp2Excl_Mll10to60,
                     ZtautauNp3Excl_Mll10to60,
                     ZtautauNp4Excl_Mll10to60,
                     ZtautauNp5Incl_Mll10to60,
                     ],
                     factor = 1.0,
                     color = palette.purple,
                     style = 'fill',
                     legendLabel = 'ZtautauJets',
                     stack = True,
                     classification = 'BG',
                     )
tt = Group('tt',
           [ttbar,
            ttbar_allhad],
#ttbar_dilepton],
            factor = 1.0,
            color = palette.pink,
            style = 'fill',
            legendLabel = 'ttbar',
            stack = True,
            classification = 'BG',
    )
SingleTop = Group('SingleTop',
                  [SingleTopSChanWenu,
                   SingleTopSChanWmunu,
                   SingleTopSChanWtaunu,
                   SingleTopWtChanIncl,
                   singletop_tchan_e,
                   singletop_tchan_mu,
                   singletop_tchan_tau],
                   factor = 1.0,
                   color = palette.red,
                   style = 'fill',
                   legendLabel = 'SingleTop',
                   stack = True,
                   classification = 'BG',
                   )
ZZ = Group('ZZ',
           [ZZ],
           factor = 1.0,
           color = palette.orange,
           style = 'fill',
           legendLabel = 'ZZ',
           stack = True,
           classification = 'BG',
           )
WW = Group('WW',
           [#WW,
            WWqqlnuNp0,
            WWqqlnuNp1,
            WWqqlnuNp2,
            WWqqlnuNp3,
            Powheg_WpWm_ee,
            Powheg_WpWm_em,
            Powheg_WpWm_et,
            Powheg_WpWm_me,
            Powheg_WpWm_mm,
            Powheg_WpWm_mt,
            Powheg_WpWm_te,
            Powheg_WpWm_tm,
            Powheg_WpWm_tt,
            gg2WW0240_WpWmenuenu,
            gg2WW0240_WpWmenumunu,
            gg2WW0240_WpWmenutaunu,
            gg2WW0240_WpWmmunuenu,
            gg2WW0240_WpWmmunumunu,
            gg2WW0240_WpWmmunutaunu,
            gg2WW0240_WpWmtaunuenu,
            gg2WW0240_WpWmtaunumunu,
            gg2WW0240_WpWmtaunutaunu],
            factor = 1.0,
            color = palette.indigo,
            style = 'fill',
            legendLabel = 'WW',
            stack = True,
            classification = 'BG',
            )
WGamma = Group('WGamma',
               [WgammaNp0,
                WgammaNp1,
                WgammaNp2,
                WgammaNp3,
                WgammaNp4,
                WgammaNp5,
                MadGraph_lnuee_lt7,
                MadGraph_lnumumu_lt7,
                MadGraph_lnutautau_lt7],
                factor = 1.0,
                color = palette.slime,
                style = 'fill',
                legendLabel = 'WGamma',
                stack = True,
                classification = 'BG',
                )
WZ = Group('WZ',
           [Powheg_WZ_W11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W15Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z15_mll3p804d0_2LeptonFilter5,
            ],
#WZ],
            factor = 1.0,
            color = palette.teal,
            style = 'fill',
            legendLabel = 'WZ',
            stack = True,
            classification = 'BG',
            )

ggF = Group('ggF',
            [ggH125_tautauhh],
            factor = 1.0,
            color = palette.slime,
            style = 'fill',
            legendLabel = 'WW',
            stack = False,
            classification = 'SIG',
            )
ZH = Group('ZH',
           [ZH125_tautauhh],
           factor = 1.0,
           color = palette.bandgreen,
           style = 'fill',
           legendLabel = 'ZH',
           stack = False,
           classification = 'SIG',
           )
VBF = Group('VBF',
            [VBFH125_tautauhh],
            factor = 1.0,
            color = palette.bandgreen,
            style = 'fill',
            legendLabel = 'VBF',
            stack = False,
            classification = 'SIG',
            )
WH = Group('WH',
           [WH125_tautauhh],
#factor = 1.0,
           factor = 100.0,
           color = palette.bandyellow,
           style = 'line',
           legendLabel = 'WH(*100)',
           stack = False,
           classification = 'SIG',
           )

                    
"""                   
                                   
AllBG = Group('AllBG',
              [ttbar,
             SingleTopSChanWenu,
             SingleTopSChanWmunu,
             SingleTopSChanWtaunu,
             SingleTopWtChanIncl,
             singletop_tchan_e,
             singletop_tchan_mu,
             singletop_tchan_tau,
             ttbar_allhad,
             ZZ,
             ZeeNp0,
             ZeeNp1,
             ZeeNp2,
             ZeeNp3,
             ZeeNp4,
             ZeeNp5incl,
             ZmumuNp0,
             ZmumuNp1,
             ZmumuNp2,
             ZmumuNp3,
             ZmumuNp4,
             ZmumuNp5incl,
             ZtautauNp0,
             ZtautauNp1,
             ZtautauNp2,
             ZtautauNp3,
             ZtautauNp4,
             ZtautauNp5incl,
             WZ,
             WWlnulnuNp0,
             WWlnulnuNp1,
             WWlnulnuNp2,
             WWlnulnuNp3,
             WWqqlnuNp0,
             WWqqlnuNp1,
             WWqqlnuNp2,
             WWqqlnuNp3,
             WpWmenuenu,
             WpWmenumunu,
             WpWmenutaunu,
             WpWmmunuenu,
             WpWmmunumunu,
             WpWmmunutaunu,
             WpWmtaunuenu,
             WpWmtaunumunu,
             WpWmtaunutaunu,
             WenuNp0,
             WenuNp1,
             WenuNp2,
             WenuNp3,
             WenuNp4,
             WenuNp5incl,
             WmunuNp0,
             WmunuNp1,
             WmunuNp2,
             WmunuNp3,
             WmunuNp4,
             WmunuNp5incl,
             WtaunuNp0,
             WtaunuNp1,
             WtaunuNp2,
             WtaunuNp3,
             WtaunuNp4,
             WtaunuNp5incl,
             ZeeNp0Excl_Mll10to60,
             ZeeNp1Excl_Mll10to60,
             ZeeNp2Excl_Mll10to60,
             ZeeNp3Excl_Mll10to60,
             ZeeNp4Excl_Mll10to60,
             ZeeNp5Incl_Mll10to60,
             ZmumuNp0Excl_Mll10to60,
             ZmumuNp1Excl_Mll10to60,
             ZmumuNp2Excl_Mll10to60,
             ZmumuNp3Excl_Mll10to60,
             ZmumuNp4Excl_Mll10to60,
             ZmumuNp5Incl_Mll10to60,
             ZtautauNp0Excl_Mll10to60,
             ZtautauNp1Excl_Mll10to60,
             ZtautauNp2Excl_Mll10to60,
             ZtautauNp3Excl_Mll10to60,
             ZtautauNp4Excl_Mll10to60,
             ZtautauNp5Incl_Mll10to60],
             factor = 1.0,
             color = palette.blue,
             style = 'fill',
             legendLabel = 'AllBG',
             stack = True,
             classification = 'BG'
             )

WH = Group('WH',
           [WH125_tautauhh],
           factor = 1.0,
           color = palette.red,
           style = 'line',
           legendLabel = 'WH',
           stack = False,
           classification = 'SIG'
           )

ZH = Group('ZH',
           [ZH125_tautauhh],
           factor = 1.0,
           color = palette.red,
           style = 'line',
           legendLabel = 'ZH',
           stack = False,
           classification = 'SIG'
           )
"""
        
