from Group import Group
from Samples import *
import palette

Data_group = Group('Data',
             [Egamma,
              JetTauEtmiss,
              Muons],
              factor = 1.0,
              classification = 'DATA'
              )
DataSSS_group = Group('DataSSS',
                [Egamma,
                 JetTauEtmiss,
                 Muons],
                 factor = 2.0,
                 classification = 'DATA'
                 )
WeJets_group = Group('WeJets',
               [WenuNp0_Auto,
                WenuNp1_Auto,
                WenuNp2_Auto,
                WenuNp3_Auto,
                WenuNp4_Auto,
                WenuNp5incl_Auto,
                ],
                factor = 1.0,
                classification = 'BG'
                )
SSSWeJets_group = Group('SSSWeJets',
                  [WenuNp0_Auto,
                   WenuNp1_Auto,
                   WenuNp2_Auto,
                   WenuNp3_Auto,
                   WenuNp4_Auto,
                   WenuNp5incl_Auto,
                   ],
                   factor = -2.0,
                   classification = 'BG'
                   )
WmJets_group = Group('WmJets',
               [WmunuNp0_Auto,
                WmunuNp1_Auto,
                WmunuNp2_Auto,
                WmunuNp3_Auto,
                WmunuNp4_Auto,
                WmunuNp5incl_Auto,
                ],
                factor = 1.0,
                classification = 'BG'
                )
SSSWmJets_group = Group('SSSWmJets',
               [WmunuNp0_Auto,
                WmunuNp1_Auto,
                WmunuNp2_Auto,
                WmunuNp3_Auto,
                WmunuNp4_Auto,
                WmunuNp5incl_Auto,
                ],
                factor = -2.0,
                classification = 'BG'
                )
WtJets_group = Group('WtJets',
               [WtaunuNp0_Auto,
                WtaunuNp1_Auto,
                WtaunuNp2_Auto,
                WtaunuNp3_Auto,
                WtaunuNp4_Auto,
                WtaunuNp5incl_Auto,
                ],
                factor = 1.0,
                classification = 'BG'
                )
SSSWtJets_group = Group('SSSWtJets',
                  [WtaunuNp0_Auto,
                   WtaunuNp1_Auto,
                   WtaunuNp2_Auto,
                   WtaunuNp3_Auto,
                   WtaunuNp4_Auto,
                   WtaunuNp5incl_Auto,
                   ],
                   factor = -2.0,
                   classification = 'BG'
                   )
ZeeJets_group = Group('ZeeJets',
                [ZeeNp0_Auto,
                 ZeeNp1_Auto,
                 ZeeNp2_Auto,
                 ZeeNp3_Auto,
                 ZeeNp4_Auto,
                 ZeeNp5incl_Auto,
                 ZeeNp0Excl_Mll10to60,
                 ZeeNp1Excl_Mll10to60,
                 ZeeNp2Excl_Mll10to60,
                 ZeeNp3Excl_Mll10to60,
                 ZeeNp4Excl_Mll10to60,
                 ZeeNp5Incl_Mll10to60,
                 ],
                 factor = 1.0,
                 classification = 'BG'
                 )
SSSZeeJets_group = Group('SSSZeeJets',
                   [ZeeNp0_Auto,
                    ZeeNp1_Auto,
                    ZeeNp2_Auto,
                    ZeeNp3_Auto,
                    ZeeNp4_Auto,
                    ZeeNp5incl_Auto,
                    ZeeNp0Excl_Mll10to60,
                    ZeeNp1Excl_Mll10to60,
                    ZeeNp2Excl_Mll10to60,
                    ZeeNp3Excl_Mll10to60,
                    ZeeNp4Excl_Mll10to60,
                    ZeeNp5Incl_Mll10to60,
                    ],
                    factor = -2.0,
                    classification = 'BG'
                    )
ZmmJets_group = Group('ZmmJets',
                [ZmumuNp0_Auto,
                 ZmumuNp1_Auto,
                 ZmumuNp2_Auto,
                 ZmumuNp3_Auto,
                 ZmumuNp4_Auto,
                 ZmumuNp5incl_Auto,
                 ZmumuNp0Excl_Mll10to60,
                 ZmumuNp1Excl_Mll10to60,
                 ZmumuNp2Excl_Mll10to60,
                 ZmumuNp3Excl_Mll10to60,
                 ZmumuNp4Excl_Mll10to60,
                 ZmumuNp5Incl_Mll10to60,
                 ],
                 factor = 1.0,
                 classification = 'BG'
                 )
SSSZmmJets_group = Group('SSSZmmJets',
                [ZmumuNp0_Auto,
                 ZmumuNp1_Auto,
                 ZmumuNp2_Auto,
                 ZmumuNp3_Auto,
                 ZmumuNp4_Auto,
                 ZmumuNp5incl_Auto,
                 ZmumuNp0Excl_Mll10to60,
                 ZmumuNp1Excl_Mll10to60,
                 ZmumuNp2Excl_Mll10to60,
                 ZmumuNp3Excl_Mll10to60,
                 ZmumuNp4Excl_Mll10to60,
                 ZmumuNp5Incl_Mll10to60,
                 ],
                 factor = -2.0,
                 classification = 'BG'
                 )
ZttJets_group = Group('ZttJets',
                [ZtautauNp0Excl_Mll10to60,
                 ZtautauNp1Excl_Mll10to60,
                 ZtautauNp2Excl_Mll10to60,
                 ZtautauNp3Excl_Mll10to60,
                 ZtautauNp4Excl_Mll10to60,
                 ZtautauNp5Incl_Mll10to60,
                 ZtautauNp0_Auto,
                 ZtautauNp1_Auto,
                 ZtautauNp2_Auto,
                 ZtautauNp3_Auto,
                 ZtautauNp4_Auto,
                 ZtautauNp5incl_Auto,
                 ],
                 factor = 1.0,
                 classification = 'BG'
                 )
SSSZttJets_group = Group('SSSZttJets',
                [ZtautauNp0Excl_Mll10to60,
                 ZtautauNp1Excl_Mll10to60,
                 ZtautauNp2Excl_Mll10to60,
                 ZtautauNp3Excl_Mll10to60,
                 ZtautauNp4Excl_Mll10to60,
                 ZtautauNp5Incl_Mll10to60,
                 ZtautauNp0_Auto,
                 ZtautauNp1_Auto,
                 ZtautauNp2_Auto,
                 ZtautauNp3_Auto,
                 ZtautauNp4_Auto,
                 ZtautauNp5incl_Auto,
                 ],
                 factor = -2.0,
                 classification = 'BG'
                 )
tt_group = Group('tt',
           [ttbar,
            ttbar_allhad,
#     ttbar_dilepton],
],
factor = 1.0,
classification = 'BG',
    )
SSStt_group = Group('SSStt',
           [ttbar,
            ttbar_allhad,
#     ttbar_dilepton],
],
factor = -2.0,
classification = 'BG',
    )
SingleTop_group = Group('SingleTop',
                  [SingleTopSChanWenu,
                   SingleTopSChanWmunu,
                   SingleTopSChanWtaunu,
                   SingleTopWtChanIncl,
                   singletop_tchan_e,
                   singletop_tchan_mu,
                   singletop_tchan_tau
                   ],
                   factor = 1.0,
                   classification = 'BG',
                   )
SSSSingleTop_group = Group('SSSSingleTop',
                  [SingleTopSChanWenu,
                   SingleTopSChanWmunu,
                   SingleTopSChanWtaunu,
                   SingleTopWtChanIncl,
                   singletop_tchan_e,
                   singletop_tchan_mu,
                   singletop_tchan_tau
                   ],
                   factor = -2.0,
                   classification = 'BG',
                   )
ZZ_group = Group('ZZ',
           [Powheg_ZZ_2e2mu_mll4_2pt5,
            Powheg_ZZ_2e2tau_mll4_2pt5,
            Powheg_ZZ_2mu2tau_mll4_2pt5,
            Powheg_ZZ_4e_mll4_2pt5,
            Powheg_ZZ_4mu_mll4_2pt5,
            Powheg_ZZ_4tau_mll4_2pt5,
            Powheg_ZZllnunu_ee_mll4,
            Powheg_ZZllnunu_mm_mll4,
            Powheg_ZZllnunu_tt_mll4,
            ],
            #ZZ],
            factor = 1.0,
            classification = 'BG',
            )
SSSZZ_group = Group('SSSZZ',
           [Powheg_ZZ_2e2mu_mll4_2pt5,
            Powheg_ZZ_2e2tau_mll4_2pt5,
            Powheg_ZZ_2mu2tau_mll4_2pt5,
            Powheg_ZZ_4e_mll4_2pt5,
            Powheg_ZZ_4mu_mll4_2pt5,
            Powheg_ZZ_4tau_mll4_2pt5,
            Powheg_ZZllnunu_ee_mll4,
            Powheg_ZZllnunu_mm_mll4,
            Powheg_ZZllnunu_tt_mll4,
            ],
            #ZZ],
            factor = -2.0,
            classification = 'BG',
            )
WW_group = Group('WW',
           [#WW,
            WWqqlnuNp0,
            WWqqlnuNp1,
            WWqqlnuNp2,
            WWqqlnuNp3,
            Powheg_WpWm_ee,
            Powheg_WpWm_em,
            Powheg_WpWm_et,
            Powheg_WpWm_me,
            Powheg_WpWm_mm,
            Powheg_WpWm_mt,
            Powheg_WpWm_te,
            Powheg_WpWm_tm,
            Powheg_WpWm_tt,
            gg2WW0240_WpWmenuenu,
            gg2WW0240_WpWmenumunu,
            gg2WW0240_WpWmenutaunu,
            gg2WW0240_WpWmmunuenu,
            gg2WW0240_WpWmmunumunu,
            gg2WW0240_WpWmmunutaunu,
            gg2WW0240_WpWmtaunuenu,
            gg2WW0240_WpWmtaunumunu,
            gg2WW0240_WpWmtaunutaunu
            ],
            factor = 1.0,
            classification = 'BG',
            )
SSSWW_group = Group('SSSWW',
           [#WW,
            WWqqlnuNp0,
            WWqqlnuNp1,
            WWqqlnuNp2,
            WWqqlnuNp3,
            Powheg_WpWm_ee,
            Powheg_WpWm_em,
            Powheg_WpWm_et,
            Powheg_WpWm_me,
            Powheg_WpWm_mm,
            Powheg_WpWm_mt,
            Powheg_WpWm_te,
            Powheg_WpWm_tm,
            Powheg_WpWm_tt,
            gg2WW0240_WpWmenuenu,
            gg2WW0240_WpWmenumunu,
            gg2WW0240_WpWmenutaunu,
            gg2WW0240_WpWmmunuenu,
            gg2WW0240_WpWmmunumunu,
            gg2WW0240_WpWmmunutaunu,
            gg2WW0240_WpWmtaunuenu,
            gg2WW0240_WpWmtaunumunu,
            gg2WW0240_WpWmtaunutaunu
            ],
            factor = -2.0,
            classification = 'BG',
            )
WGamma_group = Group('WGamma',
               [WgammaNp0,
                WgammaNp1,
                WgammaNp2,
                WgammaNp3,
                WgammaNp4,
                WgammaNp5,
                MadGraph_lnuee_lt7,
                MadGraph_lnumumu_lt7,
                MadGraph_lnutautau_lt7],
                factor = 1.0,
                classification = 'BG',
                )
SSSWGamma_group = Group('SSSWGamma',
               [WgammaNp0,
                WgammaNp1,
                WgammaNp2,
                WgammaNp3,
                WgammaNp4,
                WgammaNp5,
                MadGraph_lnuee_lt7,
                MadGraph_lnumumu_lt7,
                MadGraph_lnutautau_lt7],
                factor = -2.0,
                classification = 'BG',
                )
WZ_group = Group('WZ',
           [Powheg_WZ_W11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W15Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z15_mll3p804d0_2LeptonFilter5,
            ],
#WZ],
            factor = 1.0,
            classification = 'BG',
            )
SSSWZ_group = Group('SSSWZ',
           [Powheg_WZ_W11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_W15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_W15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_W15Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm11Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm13Z15_mll3p804d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z11_mll0p250d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z13_mll0p4614d0_2LeptonFilter5,
            Powheg_WZ_Wm15Z15_mll3p804d0_2LeptonFilter5,
            ],
#WZ],
            factor = -2.0,
            classification = 'BG',
            )                                   
WH_group = Group('WH',
           [WH125_tautauhh],
           factor = 10.0,
           classification = 'SIG'
           )
ZH_group = Group('ZH',
           [ZH125_tautauhh],
           factor = 10.0,
           classification = 'SIG'
           )









# ggF = Group('ggF',
#             [ggH125_tautauhh],
#             factor = 1.0,
#             color = palette.slime,
#             style = 'fill',
#             legendLabel = 'WW',
#             stack = False,
#             classification = 'SIG',
#             )

           # ZJetsAFII = Group('ZJetsAFII',
#                   [ZeeNp0_AFII,
#                    ZmumuNp0_AFII,
#                    ZeeNp1_AFII,
#                    ZeeNp2_AFII,
#                    ZeeNp3_AFII,
#                    ZeeNp4_AFII,
#                    ZeeNp5incl_AFII,
#                    ZmumuNp1_AFII,
#                    ZmumuNp2_AFII,
#                    ZmumuNp3_AFII,
#                    ZmumuNp4_AFII,
#                    ZmumuNp5incl_AFII],
#                    factor = 1.0,
#                    color = palette.green,
#                    style = 'fill',
#                    legendLabel = 'ZJetsAFII',
#                    stack = True,
#                    classification = 'BG'
#                    )
                        
                   
# WJetsAFII = Group('WJetsAFII',
#                   [WenuNp0_AFII,
#                    WenuNp1_AFII,
#                    WenuNp2_AFII,
#                    WenuNp3_AFII,
#                    WenuNp4_AFII,
#                    WenuNp5incl_AFII,
#                    WmunuNp0_AFII,
#                    WmunuNp1_AFII,
#                    WmunuNp2_AFII,
#                    WmunuNp3_AFII,
#                    WmunuNp4_AFII,
#                    WmunuNp5incl_AFII,
#                    WtaunuNp0_AFII,
#                    WtaunuNp1_AFII,
#                    WtaunuNp2_AFII,
#                    WtaunuNp3_AFII,
#                    WtaunuNp4_AFII,
#                    WtaunuNp5incl_AFII],
#                    factor = 1.0,
#                    color = palette.blue,
#                    style = 'fill',
#                    legendLabel = 'WJetsAFII',
#                    stack = True,
#                    classification = 'BG'
#                    )
"""
WJets = Group('WJets',
[WenuNp0_Auto,
 WmunuNp0_Auto,
 WenuNp1_Auto,
 WenuNp2_Auto,
 WenuNp3_Auto,
 WenuNp4_Auto,
 WenuNp5incl_Auto,
 WmunuNp1_Auto,
 WmunuNp2_Auto,
 WmunuNp3_Auto,
 WmunuNp4_Auto,
 WmunuNp5incl_Auto,
#WtaunuNp0_Auto,
 # WtaunuNp1_Auto,
 # WtaunuNp2_Auto,
 # WtaunuNp3_Auto,
 # WtaunuNp4_Auto,
 # WtaunuNp5incl_Auto
 ],
 factor = 1.0,
 color = palette.green,
 style = 'fill',
 legendLabel = 'WJets',
 stack = True,
 classification = 'BG'
    )
"""
"""
ZJets = Group('ZJets',
              [ZeeNp0_Auto,
               ZmumuNp0_Auto,
               ZeeNp1_Auto,
               ZeeNp2_Auto,
               ZeeNp3_Auto,
               ZeeNp4_Auto,
               ZeeNp5incl_Auto,
               ZmumuNp1_Auto,
               ZmumuNp2_Auto,
               ZmumuNp3_Auto,
               ZmumuNp4_Auto,
               ZmumuNp5incl_Auto,
               ZeeNp0Excl_Mll10to60,
               ZeeNp1Excl_Mll10to60,
               ZeeNp2Excl_Mll10to60,
               ZeeNp3Excl_Mll10to60,
               ZeeNp4Excl_Mll10to60,
               ZeeNp5Incl_Mll10to60,
               ZmumuNp0Excl_Mll10to60,
               ZmumuNp1Excl_Mll10to60,
               ZmumuNp2Excl_Mll10to60,
               ZmumuNp3Excl_Mll10to60,
               ZmumuNp4Excl_Mll10to60,
               ZmumuNp5Incl_Mll10to60,
               ZtautauNp0Excl_Mll10to60,
               ZtautauNp0_Auto,
               ZtautauNp1_Auto,
               ZtautauNp2_Auto,
               ZtautauNp3_Auto,
               ZtautauNp4_Auto,
               ZtautauNp5incl_Auto,
               ZtautauNp1Excl_Mll10to60,
               ZtautauNp2Excl_Mll10to60,
               ZtautauNp3Excl_Mll10to60,
               ZtautauNp4Excl_Mll10to60,
               ZtautauNp5Incl_Mll10to60
               ],
# #factor = 0.80916,#factor when plotting is_WHlephad
factor = 1.0,
color = palette.blue,
style = 'fill',
legendLabel = 'ZJets',
stack = True,
classification = 'BG'
)
"""
        
